[build]
  command = "npm run build"
  publish = "dist"
  base = "/"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  # Explicitly tell Netlify this is not a Next.js site
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NPM_FLAGS = "--no-optional"
  # Add build optimization flags
  NODE_OPTIONS = "--max-old-space-size=4096"
  VITE_CJS_IGNORE_WARNING = "true"

# Disable Next.js plugin detection
[build.processing]
  skip_processing = false

# Custom headers to help prevent Next.js auto-detection
[[headers]]
  for = "/*"
  [headers.values]
    X-Framework = "Vite"
    Cache-Control = "public, max-age=31536000, immutable"

# Add security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
