
[build]
  command = "npm run build"
  publish = "dist"
  base = "/"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  # Explicitly tell Netlify this is not a Next.js site
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NPM_FLAGS = "--no-optional"

# Disable Next.js plugin detection
[build.processing]
  skip_processing = false

# Custom headers to help prevent Next.js auto-detection
[[headers]]
  for = "/*"
  [headers.values]
    X-Framework = "Vite"
