
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfrutnkohrviouttwsnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmcnV0bmtvaHJ2aW91dHR3c251Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MTQ5NTgsImV4cCI6MjA1ODE5MDk1OH0.ohyxAjqesiCyofKgoNcuRMpMdeB8W1dd2paWEbJjVl4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Configure the client with proper settings to handle token refresh and session persistence
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'implicit',
  },
  global: {
    headers: { 'x-application-name': 'store-management' },
  },
  realtime: {
    params: {
      eventsPerSecond: 1, // Reduce rate limiting by limiting events
    }
  },
  // Add these settings to improve reliability
  db: {
    schema: 'public',
  },
  // Add request throttling to avoid rate limit errors
  requestTransformer: (req, nextHandler) => {
    // Add a small random delay to stagger requests
    const delay = Math.random() * 300;
    setTimeout(() => nextHandler(req), delay);
  }
});

// Helper function to safely handle Supabase queries with proper typing
export function asStringParam(param: string | number | boolean): string {
  return param as unknown as string;
}

/**
 * Fix for JWT token expiration issues
 * This ensures we don't have tokens with excessively long expiration times
 */
export async function fixJwtTokenIfNeeded() {
  try {
    const { data: session } = await supabase.auth.getSession();
    if (!session.session) return;
    
    const token = session.session.access_token;
    if (!token) return;
    
    // Parse JWT to check expiration
    const payload = JSON.parse(atob(token.split('.')[1]));
    const expTime = payload.exp * 1000; // Convert to milliseconds
    const now = Date.now();
    
    // If token expires more than 1 hour from now, refresh it
    // This prevents issues with excessively long expiration times
    if (expTime - now > 3600000 || expTime < now) {
      console.log("Refreshing access token to fix expiration time");
      await supabase.auth.refreshSession();
    }
  } catch (e) {
    console.error("Error checking JWT token:", e);
  }
}
