
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfrutnkohrviouttwsnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmcnV0bmtvaHJ2aW91dHR3c251Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MTQ5NTgsImV4cCI6MjA1ODE5MDk1OH0.ohyxAjqesiCyofKgoNcuRMpMdeB8W1dd2paWEbJjVl4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Queue for rate-limiting requests
const requestQueue: Array<() => Promise<void>> = [];
let isProcessingQueue = false;

// Process requests from the queue
async function processQueue() {
  if (isProcessingQueue || requestQueue.length === 0) return;
  
  isProcessingQueue = true;
  
  try {
    // Process requests with a delay between them
    while (requestQueue.length > 0) {
      const request = requestQueue.shift();
      if (request) {
        await request();
        // Add a small delay between requests to prevent rate limiting
        await new Promise(resolve => setTimeout(resolve, 300));
      }
    }
  } finally {
    isProcessingQueue = false;
  }
}

// Configure the client with proper settings to handle token refresh and session persistence
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'implicit',
  },
  global: {
    headers: { 'x-application-name': 'store-management' },
  },
  realtime: {
    params: {
      eventsPerSecond: 1, // Reduce rate limiting by limiting events
    }
  },
  // Add these settings to improve reliability
  db: {
    schema: 'public',
  },
  // Add request throttling to avoid rate limit errors
  requestTransformer: (req, nextHandler) => {
    // Add to queue instead of random delay
    requestQueue.push(() => new Promise<void>((resolve) => {
      nextHandler(req);
      resolve();
    }));
    
    // Start processing the queue if not already
    setTimeout(() => {
      processQueue();
    }, 0);
  }
});

// Helper function to safely handle Supabase queries with proper typing
export function asStringParam(param: string | number | boolean): string {
  return param as unknown as string;
}

/**
 * Fix for JWT token expiration issues
 * This ensures we don't have tokens with excessively long expiration times
 */
export async function fixJwtTokenIfNeeded() {
  try {
    const { data: session } = await supabase.auth.getSession();
    if (!session.session) return;
    
    const token = session.session.access_token;
    if (!token) return;
    
    // Parse JWT to check expiration
    const payload = JSON.parse(atob(token.split('.')[1]));
    const expTime = payload.exp * 1000; // Convert to milliseconds
    const now = Date.now();
    
    // If token expires more than 1 hour from now, refresh it
    // This prevents issues with excessively long expiration times
    if (expTime - now > 3600000 || expTime < now) {
      console.log("Refreshing access token to fix expiration time");
      await supabase.auth.refreshSession();
    }
  } catch (e) {
    console.error("Error checking JWT token:", e);
  }
}

// Rate limiting cache
const rateLimitCache = new Map<string, { timestamp: number, count: number }>();

/**
 * Helper to check if a request should be rate limited
 * @param key Unique identifier for the request type
 * @param maxRequests Maximum requests allowed per window
 * @param windowMs Time window in milliseconds
 * @returns Boolean indicating if the request should be throttled
 */
export function shouldRateLimit(key: string, maxRequests = 5, windowMs = 1000): boolean {
  const now = Date.now();
  const cacheKey = `rate_limit_${key}`;
  
  // Get or initialize cache entry
  const entry = rateLimitCache.get(cacheKey) || { timestamp: now, count: 0 };
  
  // Reset if window has passed
  if (now - entry.timestamp > windowMs) {
    entry.timestamp = now;
    entry.count = 1;
    rateLimitCache.set(cacheKey, entry);
    return false;
  }
  
  // Check if limit is exceeded
  if (entry.count >= maxRequests) {
    return true;
  }
  
  // Increment counter
  entry.count++;
  rateLimitCache.set(cacheKey, entry);
  return false;
}
