
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfrutnkohrviouttwsnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmcnV0bmtvaHJ2aW91dHR3c251Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MTQ5NTgsImV4cCI6MjA1ODE5MDk1OH0.ohyxAjqesiCyofKgoNcuRMpMdeB8W1dd2paWEbJjVl4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'implicit',
  },
  global: {
    headers: { 'x-application-name': 'store-management' },
  },
  realtime: {
    params: {
      eventsPerSecond: 2, // Limit realtime events to avoid rate limiting
    }
  }
});
